./cmc parallel invoke --loopNum=10000 --threadNum=7500 --printTime=5 --timeout=36000 --sleepTime=400 --climbTime=5 \
--use-tls=true --showKey=false --contract-name="RECEPIT" --method="Save" \
--pairs="[{\"value\":\"1100,3100,4400\",\"key\":\"wPars\",\"unique\":false},{\"value\":\"1100,3100,4400\",\"key\":\"rPars\",\"unique\":false},{\"value\":\"123\",\"key\":\"bizId\",\"unique\":true},{\"value\":\"1665556413\",\"key\":\"timestamp\",\"unique\":false},{\"value\":\"1665556413\",\"key\":\"reqSign\",\"unique\":false},{\"value\":\"FP_\",\"key\":\"businessType\",\"unique\":false},{\"value\":\"1\",\"key\":\"chainName\",\"unique\":false},{\"value\":\"test\",\"key\":\"mutableContent\",\"unique\":false},{\"value\":\"testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest\",\"key\":\"immutableContent\",\"unique\":false}]" \
--org-IDs="wx-org.chainmaker.org" --hosts="192.168.1.5:12301" --auth-type=1 --hash-algorithm=SM3 \
--user-keys="./testdata/crypto-config/wx-org.chainmaker.org/user/client1/client1.sign.key" \
--user-crts="./testdata/crypto-config/wx-org.chainmaker.org/user/client1/client1.sign.crt" \
--ca-path="./testdata/crypto-config/wx-org.chainmaker.org/ca" \
--admin-sign-keys="./testdata/crypto-config/wx-org.chainmaker.org/user/admin1/admin1.sign.key" \
--admin-sign-crts="./testdata/crypto-config/wx-org.chainmaker.org/user/admin1/admin1.sign.crt" \
--chain-id=chain_zj --alias=00000000000
