./cmc client contract user invoke \
--contract-name=REAL_ESTATE \
--method=Save \
--params="{\"immutableContent\":\"不可修改数据\",\"mutableContent\":\"可修改数据\",\"chainName\":\"1\",\"businessType\":\"FP_\",\"reqSign\":\"1665556413\",\"wPars\":\"13100000000,14400000000\",\"rPars\":\"13100000000,14400000000\",\"timestamp\":\"1665556413\",\"bizId\":\"thisisbi321zid02\"}" \
--sync-result=true \
--sdk-conf-path=./testdata/signle-org/scso_zj_client_1100.yml


./cmc parallel invoke --loopNum=10000 --threadNum=7500 --printTime=5 --timeout=36000 --sleepTime=400 --climbTime=5 \
--use-tls=true --showKey=false --contract-name="REAL_ESTATE" --method="Save" \
--pairs="[{\"value\":\"13100000000,14400000000\",\"key\":\"wPars\",\"unique\":false},{\"value\":\"13100000000,14400000000\",\"key\":\"rPars\",\"unique\":false},{\"value\":\"123\",\"key\":\"bizId\",\"unique\":false},{\"value\":\"1665556413\",\"key\":\"timestamp\",\"unique\":false},{\"value\":\"1665556413\",\"key\":\"reqSign\",\"unique\":false},{\"value\":\"FP_\",\"key\":\"businessType\",\"unique\":false},{\"value\":\"1\",\"key\":\"chainName\",\"unique\":false},{\"value\":\"test\",\"key\":\"mutableContent\",\"unique\":false},{\"value\":\"testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest\",\"key\":\"immutableContent\",\"unique\":false}]" \
--org-IDs="wx-org.chainmaker.org" --hosts="192.168.1.5:12301" --auth-type=1 --hash-algorithm=SM3 \
--user-keys="./testdata/crypto-config/wx-org.chainmaker.org/user/client1/client1.sign.key" \
--user-crts="./testdata/crypto-config/wx-org.chainmaker.org/user/client1/client1.sign.crt" \
--ca-path="./testdata/crypto-config/wx-org.chainmaker.org/ca" \
--admin-sign-keys="./testdata/crypto-config/wx-org.chainmaker.org/user/admin1/admin1.sign.key" \
--admin-sign-crts="./testdata/crypto-config/wx-org.chainmaker.org/user/admin1/admin1.sign.crt" \
--chain-id=chain_zj --alias=00000000000
